app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'BlogController@home');
Route::get('/about','BlogController@about');
Route::get('/contact','BlogController@contact');
Route::resource('/posts','PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $fillable = ['title', 'body'];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class BlogController extends Controller
{
    //
    function home(){
    	return view("welcome");
    }

    function about(){
    	return view("about");
    }

    function contact(){
    	return view("contact");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Post;
use Session;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $posts = Post::all();
        return view("posts.index")->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view("posts.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, array(
                    'title' => 'required|max:255',
                    'body'  => 'required'
            ));
        //echo $request->title;
        $post = new Post;
        $post->title = $request->title;
        $post->body = $request->body;
        $post->save();
        Session::flash("success","Successfuly saved");
        return redirect()->route("posts.show",$post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view("posts.show")->withPost($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $post = Post::find($id);
        return view("posts.edit")->withPost($post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
                'title' => 'required|max:255',
                'body' => 'required'
            ]);

        $post = Post::find($id);
        $post->title = $request->input('title');
        $post->body = $request->input('body');
        $post->save();

        Session::flash("success","Post Successfuly updated");
        return redirect()->route("posts.show", $post->id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $post = Post::find($id);
        $post->destroy($id);
        return redirect()->route('posts.index');
    }
}

resources/views/about.blade.php
@extends("base.base")
@section("title","| About")
@section("activeAbout", "active")
@section("page-content")
    <div class="container">

      <div class="row">
        <div class="col-md-12">
          <h1>About Me</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis aspernatur quas quibusdam veniam sunt animi, est quos optio explicabo deleniti inventore unde minus, tempore enim ratione praesentium, cumque, dolores nesciunt?</p>
        </div>
      </div>

    </div>
    <!-- end of .container -->
@stop

resources/views/base/base.blade.php
@include("partials._header")
@include("partials._nav")

@include("partials._messages")
@yield('page-content')


@include("partials._footer")

resources/views/contact.blade.php
@extends("base.base")

@section("title","| Contact")
@section("activeContact", "active")
@section("page-content")
    <div class="container">

      <div class="row">
        <div class="col-md-12">
          <h1>Contact Me</h1>
          <hr>
          <form>
            <div class="form-group">
              <label name="email">Email:</label>
              <input id="email" name="email" class="form-control">
            </div>

            <div class="form-group">
              <label name="subject">Subject:</label>
              <input id="subject" name="subject" class="form-control">
            </div>

            <div class="form-group">
              <label name="message">Message:</label>
              <textarea id="message" name="message" class="form-control">Type your message here...</textarea>
            </div>

            <input type="submit" value="Send Message" class="btn btn-success">
          </form>
        </div>
      </div>

    </div>
    <!-- end of .container -->
@stop

resources/views/partials/_footer.blade.php
<hr>
<p class="text-center">Copyright © 2016</p>
</div>
  </body>

</html>

resources/views/partials/_header.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@yield('title')</title>
     <!-- CHANGE THIS TITLE FOR EACH PAGE -->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


  </head>
  <body>
  <div class="container"> <!-- wrapper -->

resources/views/partials/_messages.blade.php
@if(Session::has("success"))

<div class="alert alert-success">
	<strong>{{Session::get('success')}}</strong>
</div>
@endif

@if(count($errors))

<div class="alert alert-danger">
	<strong>Errors:</strong>
	<ul>
	@foreach($errors->all() as $error)
		<li>{{$error}}</li>
	@endforeach
	</ul>
</div>
@endif

resources/views/partials/_nav.blade.php
    <!-- Default Bootstrap Navbar -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Laravel Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="@yield("activeHome")"><a href="/">Home</a></li>
            <li class="@yield("activeAbout")"><a href="/about">About</a></li>
            <li class="@yield("activeContact")"><a href="/contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>

resources/views/posts/create.blade.php
@extends("base.base")
@section("activeHome", "active")


@section("page-content")
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Create New Post</h1>	
		<hr>
		<form action="{{ route('posts.store') }}" method="post">
			<input type="hidden" name="_token" value="{{ csrf_token() }}">
		  <div class="form-group">
		    <label for="title">Title</label>
		    <input type="text" class="form-control" id="title" placeholder="Title" name="title">
		  </div>
		  <div class="form-group">
		  	<label for="body">Body</label>
		  	<textarea class="form-control" id="body" name="body"></textarea>
		  </div>
		  <button type="submit" class="btn btn-default" id="submit1">Submit</button>
		</form>
	</div>
	</div>
@endsection

resources/views/posts/edit.blade.php
@extends("base.base")
@section('title', "| Edit post")
@section('activeHome', "active")

@section('page-content')
	<div class="row">
	<div class="col-md-8">
		<form method="post" action="{{ route('posts.update', ['id' => $post->id]) }}">
		<input type="hidden" name="_token" value="{{csrf_token()}}">
		<input type="hidden" name="_method" value="PUT"></input>
		<label for="title">Title</label>
		<input type='text' class='form-control' name= "title" value="{{ $post->title }}">
		<label for="body">Body</label>
		<textarea id="body" cols="30" rows="10" class="form-control" name="body">{{ $post->body }}</textarea>
			
		
	</div>

	<div class="col-md-4">
		<div class="well">
			<dl class="dl-horizontal">
				<dt>Created At:</dt>
				<dd>{{date('d M,Y H:i a',strtotime($post->created_at))}}</dd>
			</dl>
			<dl class="dl-horizontal">
				<dt>Updated At</dt>
				<dd>{{date('d M,Y H:i a',strtotime($post->updated_at))}}</dd>
			</dl>
			<hr>
			<div class="row">
				<div class="col-sm-6">
					<a href="{{ route('posts.show', ['id' => $post->id]) }}" class="btn btn-danger btn-block">Cancel</a>
				</div>
				<div class="col-sm-6">
					<input type="submit" class="btn btn-success btn-block" name="submit" value="Save">
				</div>
			</div>
		</div>
	</div>
	</form> <!-- end of form -->
	</div>
@endsection

resources/views/posts/index.blade.php
@extends('base.base')
@section('title', '| All posts')
@section("activeHome", "active")

@section('page-content')
	
	<div class="row">
	<div class="col-md-10">
		<h1>Posts</h1>
	</div>
	<div class="col-md-2 h1-parallel">
		<a href="{{route('posts.create')}}" class="btn btn-primary btn-block">Create New</a>
	</div>
	</div>
		
    <div class="row">
        <div class="col-md-12">

      
      	<table class="table">
      		<thead>
      			<th>#</th>
      			<th>Title</th>
      			<th>Body</th>
      			<th>Created At</th>
      			<th>Updated At</th>
      		</thead>
      		<tbody>
      			@foreach($posts as $post)
      			<tr>
      				<td>{{$post->id}}</td>
					<td>{{$post->title}}</td>
					<td>{{substr($post->body, 0, 20)}}{{(strlen($post->body)>20)?"  ...":""}}</td>
					<td>{{date('d M Y H:i a',strtotime($post->created_at))}}</td>
					<td>{{date('d M Y H:i a',strtotime($post->updated_at))}}</td>
					<td><a href="{{ route('posts.show', ['id' => $post->id]) }}" class="btn btn-default">Read</a>
					<a href="{{ route('posts.edit', $post->id) }}" class="btn btn-default">Edit</a>
					</td>
      			</tr>
      			@endforeach
      		</tbody>
      	</table>
        </div>
    </div>
@endsection

resources/views/posts/show.blade.php
@extends("base.base")
@section("title", "| show posts")
@section("activeHome", "active")

@section("page-content")
<div class="row">
	<div class="col-md-8">
		<h1>{{$post->title}}</h1>
		<p>{{$post->body}}</p>	
	</div>

	<div class="col-md-4">
		<div class="well">
			<dl class="dl-horizontal">
				<dt>Created At:</dt>
				<dd>{{date('d M Y H:i a',strtotime($post->created_at))}}</dd>
			</dl>
			<dl class="dl-horizontal">
				<dt>Updated At</dt>
				<dd>{{date('d M Y H:i a',strtotime($post->updated_at))}}</dd>
			</dl>
			<hr>
			<div class="row">
				<div class="col-sm-6">
					<a href="{{ route('posts.edit', ['id' => $post->id]) }}" class="btn btn-primary btn-block">Edit</a>
				</div>
				<div class="col-sm-6">
					<form method="post" action="{{ route('posts.destroy', ['id' => $post->id]) }}">
					{!! csrf_field() !!}
					<input type="hidden" name="_method" value="DELETE">
					<input type="submit" class="btn btn-danger btn-block" value="Delete">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
	
@endsection